# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: letanphuc
      url-base: https://github.com/letanphuc

  projects:
    - name: wasm-micro-runtime
      remote: letanphuc
      revision: main
      path: modules/wasmmicroruntime
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - hal_espressif # required by ESP32-S3 boards
          - fatfs         # FatFS payload/config storage
          - mbedtls       # TLS support for the management server
          - tf-psa-crypto # PSA crypto backend used by Wi-Fi security
          - mcuboot       # firmware update and rollback support
