#!/usr/bin/env python3
"""Generate the WebOS C and Rust SDK declarations from abi/webos-v1.yaml."""
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[1]
spec = yaml.safe_load((ROOT / "abi/webos-v1.yaml").read_text())
major, minor = map(int, spec["abi"]["version"].split("."))
errors = spec["errors"]
levels = spec["log_levels"]

c = f"""/* Generated by scripts/generate_abi.py; do not edit. */
#ifndef WEBOS_ABI_V1_H
#define WEBOS_ABI_V1_H
#ifdef __cplusplus
extern "C" {{
#endif
#define WEBOS_ABI_MAJOR {major}u
#define WEBOS_ABI_MINOR {minor}u
#define WEBOS_ABI_VERSION ((WEBOS_ABI_MAJOR << 16) | WEBOS_ABI_MINOR)
#define WEBOS_ABI_MAX_IO_BYTES {spec['limits']['max_io_bytes']}u
#define WEBOS_ABI_MAX_PATH_BYTES {spec['limits']['max_path_bytes']}u
"""
c += "enum webos_error {\n" + "".join(f"  WEBOS_{k} = {v},\n" for k,v in errors.items()) + "};\n"
c += "enum webos_log_level {\n" + "".join(f"  WEBOS_LOG_{k} = {v},\n" for k,v in levels.items()) + "};\n"
c_types = {"u32": "unsigned int", "i32": "int", "const_ptr": "const void *", "ptr": "void *", "cstr": "const char *"}
for function in spec["functions"]:
    result = "void" if function["result"] == "void" else c_types[function["result"]]
    params = ", ".join(f"{c_types[param_type]} {name}" for name, param_type in function["params"]) or "void"
    c += f"{result} {function['name']}({params});\n"
c += """#define WEBOS_LOG_TEXT(text) webos_log(WEBOS_LOG_INFO, (text), (unsigned int)(sizeof(text) - 1u))
/* Optional webos.http/1 extension; the host returns WEB_HTTP_ERR_DENIED without a grant. */
enum web_http_method { WEB_HTTP_GET, WEB_HTTP_POST, WEB_HTTP_PUT, WEB_HTTP_DELETE, WEB_HTTP_PATCH, WEB_HTTP_HEAD };
enum web_http_error { WEB_HTTP_OK = 0, WEB_HTTP_ERR_INVALID = -1, WEB_HTTP_ERR_NO_NETWORK = -2,
  WEB_HTTP_ERR_DNS = -3, WEB_HTTP_ERR_CONNECT = -4, WEB_HTTP_ERR_TLS = -5, WEB_HTTP_ERR_TIMEOUT = -6,
  WEB_HTTP_ERR_TOO_LARGE = -7, WEB_HTTP_ERR_IO = -8, WEB_HTTP_ERR_DENIED = -9,
  WEB_HTTP_ERR_BUSY = -10, WEB_HTTP_ERR_UNSUPPORTED = -11 };
enum web_http_response_flags { WEB_HTTP_RESPONSE_TRUNCATED = 1u << 0, WEB_HTTP_RESPONSE_LENGTH_UNKNOWN = 1u << 1 };
struct web_http_response { unsigned int struct_size, status_code, body_len, content_length, flags; };
int web_http_request(unsigned int method, const char *url, unsigned int url_len, const void *headers,
  unsigned int headers_len, const void *request_body, unsigned int request_body_len, void *response_body,
  unsigned int response_capacity, struct web_http_response *response, unsigned int response_size,
  unsigned int timeout_ms);
#define WEBOS_DECLARE_ABI_VERSION() enum { webos_abi_declared_version = WEBOS_ABI_VERSION };
#ifdef __cplusplus
}
#endif
#endif
"""

r = f"""// Generated by scripts/generate_abi.py; do not edit.
pub const WEBOS_ABI_MAJOR: u32 = {major};
pub const WEBOS_ABI_MINOR: u32 = {minor};
pub const WEBOS_ABI_VERSION: u32 = (WEBOS_ABI_MAJOR << 16) | WEBOS_ABI_MINOR;
pub const WEBOS_ABI_MAX_IO_BYTES: u32 = {spec['limits']['max_io_bytes']};
pub const WEBOS_ABI_MAX_PATH_BYTES: u32 = {spec['limits']['max_path_bytes']};
"""
for k,v in errors.items(): r += f"pub const WEBOS_{k}: i32 = {v};\n"
for k,v in levels.items(): r += f"pub const WEBOS_LOG_{k}: u32 = {v};\n"
rust_types = {"u32": "u32", "i32": "i32", "const_ptr": "*const u8", "ptr": "*mut u8", "cstr": "*const u8"}
r += "unsafe extern \"C\" {\n"
for function in spec["functions"]:
    params = ", ".join(f"{name}: {rust_types[param_type]}" for name, param_type in function["params"])
    result = "" if function["result"] == "void" else f" -> {rust_types[function['result']]}"
    r += f"    pub fn {function['name']}({params}){result};\n"
r += """}
// Optional webos.http/1 extension; the host returns WEB_HTTP_ERR_DENIED without a grant.
pub const WEB_HTTP_GET: u32 = 0;
pub const WEB_HTTP_POST: u32 = 1;
pub const WEB_HTTP_PUT: u32 = 2;
pub const WEB_HTTP_DELETE: u32 = 3;
pub const WEB_HTTP_PATCH: u32 = 4;
pub const WEB_HTTP_HEAD: u32 = 5;
pub const WEB_HTTP_OK: i32 = 0;
pub const WEB_HTTP_ERR_INVALID: i32 = -1;
pub const WEB_HTTP_ERR_NO_NETWORK: i32 = -2;
pub const WEB_HTTP_ERR_DNS: i32 = -3;
pub const WEB_HTTP_ERR_CONNECT: i32 = -4;
pub const WEB_HTTP_ERR_TLS: i32 = -5;
pub const WEB_HTTP_ERR_TIMEOUT: i32 = -6;
pub const WEB_HTTP_ERR_TOO_LARGE: i32 = -7;
pub const WEB_HTTP_ERR_IO: i32 = -8;
pub const WEB_HTTP_ERR_DENIED: i32 = -9;
pub const WEB_HTTP_ERR_BUSY: i32 = -10;
pub const WEB_HTTP_ERR_UNSUPPORTED: i32 = -11;
pub const WEB_HTTP_RESPONSE_TRUNCATED: u32 = 1 << 0;
pub const WEB_HTTP_RESPONSE_LENGTH_UNKNOWN: u32 = 1 << 1;
#[repr(C)]
pub struct WebHttpResponse {
    pub struct_size: u32,
    pub status_code: u32,
    pub body_len: u32,
    pub content_length: u32,
    pub flags: u32,
}
unsafe extern "C" {
    pub fn web_http_request(
        method: u32,
        url: *const u8,
        url_len: u32,
        headers: *const u8,
        headers_len: u32,
        request_body: *const u8,
        request_body_len: u32,
        response_body: *mut u8,
        response_capacity: u32,
        response: *mut WebHttpResponse,
        response_size: u32,
        timeout_ms: u32,
    ) -> i32;
}
#[macro_export]
macro_rules! webos_declare_abi_version {
    () => {
        #[used]
        #[unsafe(link_section = ".custom_section.webos.abi")]
        static WEBOS_ABI_METADATA: [u8; 4] = [WEBOS_ABI_MINOR as u8, 0, WEBOS_ABI_MAJOR as u8, 0];
    };
}
"""
text_outputs = [(ROOT/'sdk/c/webos.h', c), (ROOT/'sdk/rust/webos.rs', r)]
binary_output = (ROOT / 'sdk/webos-abi-v1.bin', ((major << 16) | minor).to_bytes(4, 'little'))
for path, data in text_outputs:
    if '--check' in sys.argv:
        if not path.exists() or path.read_text() != data:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr); sys.exit(1)
    else:
        path.write_text(data)
path, data = binary_output
if '--check' in sys.argv:
    if not path.exists() or path.read_bytes() != data:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr); sys.exit(1)
else:
    path.write_bytes(data)
