// Generated by scripts/generate_abi.py; do not edit.
pub const WEBOS_ABI_MAJOR: u32 = 1;
pub const WEBOS_ABI_MINOR: u32 = 0;
pub const WEBOS_ABI_VERSION: u32 = (WEBOS_ABI_MAJOR << 16) | WEBOS_ABI_MINOR;
pub const WEBOS_ABI_MAX_IO_BYTES: u32 = 65536;
pub const WEBOS_ABI_MAX_PATH_BYTES: u32 = 255;
pub const WEBOS_OK: i32 = 0;
pub const WEBOS_INVALID: i32 = -1;
pub const WEBOS_DENIED: i32 = -2;
pub const WEBOS_NOT_FOUND: i32 = -3;
pub const WEBOS_IO: i32 = -4;
pub const WEBOS_TOO_LARGE: i32 = -5;
pub const WEBOS_BUSY: i32 = -6;
pub const WEBOS_UNSUPPORTED: i32 = -7;
pub const WEBOS_LOG_ERROR: u32 = 1;
pub const WEBOS_LOG_WARN: u32 = 2;
pub const WEBOS_LOG_INFO: u32 = 3;
pub const WEBOS_LOG_DEBUG: u32 = 4;
unsafe extern "C" {
    pub fn webos_log(level: u32, data: *const u8, length: u32);
    pub fn webos_sleep_ms(milliseconds: u32);
    pub fn webos_read(path: *const u8, data: *mut u8, capacity: u32) -> i32;
    pub fn webos_write(path: *const u8, data: *const u8, length: u32) -> i32;
    pub fn webos_ready();
    pub fn webos_heartbeat();
}
#[macro_export]
macro_rules! webos_declare_abi_version {
    () => {
        #[used]
        #[unsafe(link_section = ".custom_section.webos.abi")]
        static WEBOS_ABI_METADATA: [u8; 4] = [WEBOS_ABI_MINOR as u8, 0, WEBOS_ABI_MAJOR as u8, 0];
    };
}
